### ISSUE TITLE
Add tableschema-jl to pkg.julialang.org

### ISSUE THREAD

**Issue by serahrono** [frictionlessdata/TableSchema.jl#24]
Get tableschema-jl published as a registered Julia library on [pkg.julialang.org/](http://pkg.julialang.org/)

Guide: https://docs.julialang.org/en/v0.6.3/manual/packages/#Tagging-and-Publishing-Your-Package-1

**Comment by roll** [comment]
@loleg 
It should be totally fine. @serahrono would you like to handle this renaming/publishing?

**Comment by scls19fr** [comment]
https://github.com/attobot/attobot can help for publishing release.
https://github.com/JuliaComputing/FemtoCleaner.jl can also help to automatically fix depreciations.
Maybe someone which is allowed to do it should enable these 2 bots (after renaming repositories to avoid side effects)

**Comment by serahrono** [comment]
On it @roll

**Comment by scls19fr** [comment]
So my short term plan would be:
- read https://docs.julialang.org/en/latest/stdlib/Pkg/ and https://discourse.julialang.org/t/ann-introducing-upgradathon-fridays/12047/3 to be aware of what are Julia 0.7/1.0 changes in package development
- rename repositories (https://github.com/frictionlessdata/tableschema-jl/ and https://github.com/frictionlessdata/datapackage-jl/ to fit with Julia package naming conventions)
- install FemtoCleaner
- drop Julia 0.6 support and have Julia 0.7 as reference for implementation (when modifying https://github.com/frictionlessdata/tableschema-jl/blob/master/REQUIRE FemtoCleaner should probably find some depreciations)
- test both Julia 0.7 and Julia 1.0 in CI
- install attobot and publish release by creating a first Github tag (and see if a PR is created at https://github.com/JuliaLang/METADATA.jl )

**Comment by loleg** [comment]
Thanks all!

**Comment by serahrono** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/18531

**Comment by scls19fr** [comment]
Not sure it will be merged as nighly version doesn't pass ci (the problem being in fact with julia 1.0)

**Comment by scls19fr** [comment]
https://github.com/frictionlessdata/TableSchema.jl/pull/33 adds Julia 1.0 to CI (but it's currently broken) and adds nightly to allowed failures.

**Comment by loleg** [comment]
All builds are now green with #40 
The package seems to have been approved, and should go out in the next update of METADATA.

**Comment by loleg** [comment]
There is an issue in the Julia package manager that is preventing our package from showing up in the website, which has not been updated since August due to the 1.0 release and transitioning maintainers. See https://github.com/JuliaCI/PackageEvaluator.jl/issues/207

Nevertheless, TableSchema installs just fine in the current Julia release. This should help our release of DataPackage.jl and subsequent activities.
