### ISSUE TITLE
Explicit string decoding of table data

### ISSUE THREAD

**Issue by loleg** [frictionlessdata/TableSchema.jl#28]
In the future release of Julia, the `readdlm` function will break on non-UTF-8 formatted strings. Use [StringEncodings.jl](https://github.com/JuliaStrings/StringEncodings.jl) or [Strs.jl](https://github.com/JuliaString/Strs.jl) on the I/O stream.

Via https://travis-ci.org/loleg/TableSchema.jl/jobs/435294732

**Comment by scls19fr** [comment]
Why not using https://github.com/JuliaData/CSV.jl or https://github.com/queryverse/CSVFiles.jl for reading delimited files?
